"""Add the one to many relationship between seller<->shipment and  delivery_partner<->shipment

Revision ID: 308ece5d8d3e
Revises: 0ee9c34d9e81
Create Date: 2025-10-20 13:58:59.397208

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308ece5d8d3e'
down_revision: Union[str, Sequence[str], None] = '0ee9c34d9e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('seller_id', sa.Uuid(), nullable=False))
    op.add_column('shipments', sa.Column('partner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipments', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'shipments', 'delivery_partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'partner_id')
    op.drop_column('shipments', 'seller_id')
    # ### end Alembic commands ###
