"""Add estimated_delivery to the shipments table

Revision ID: 6d4d38a9c3f1
Revises: 5a8d56936f9c
Create Date: 2025-10-21 20:32:59.268452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d4d38a9c3f1'
down_revision: Union[str, Sequence[str], None] = '5a8d56936f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('estimated_delivery', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'estimated_delivery')
    # ### end Alembic commands ###
