"""Remove the password column from Sellers and DeliveryPartners tables

Revision ID: 74cde4c9ed89
Revises: bd4cd9bc2847
Create Date: 2025-10-21 12:30:50.844009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74cde4c9ed89'
down_revision: Union[str, Sequence[str], None] = 'bd4cd9bc2847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partners', 'password')
    op.drop_column('sellers', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('delivery_partners', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
