"""Update shipment partner_id to allow null

Revision ID: aec74b115bac
Revises: 308ece5d8d3e
Create Date: 2025-10-20 14:42:31.580371

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec74b115bac'
down_revision: Union[str, Sequence[str], None] = '308ece5d8d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'partner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'partner_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
